image: eve-measure-config
org: eriknordmark

config:
  binds:
    - /:/hostfs
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /run:/run
    - /var:/var
    - /persist:/persist:rshared,rbind
    - /config:/config:rshared,rbind
    - /containers:/containers:rshared,rbind
  rootfsPropagation: shared
  capabilities:
    - all
  devices:
    - path: all
      type: a
# package tag bump for signing
